sudo: required
language: python
services:
  - docker
python:
  - "3.9"
install: "pip install -r requirement.txt"
script:
  - python -m unittest test.py
  - coverage run test.py

  - echo "cps847cps847" | docker login -u "andrewlee847" --password-stdin
  - docker push andrewlee847/dockertest
after_success: bash <(curl -s https://codecov.io/bash)
