sudo: required
language: python
services:
  - docker
python:
  - "3.9"
install: "pip install -r requirement.txt"
script:
  - python -m unittest test.py
  - coverage run test.py

  - docker image build -t andrewlee847/dockertest .

after_success: 
  - bash <(curl -s https://codecov.io/bash)

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andrewlee847/dockertest


deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "dtest"
  env: "Dtest-env"
  bucket_name: "elasticbeanstalk-us-east-2-683233913294"
  on:
    branch: main
